### ISSUE TITLE
[Bug]: Error with FramedBlocks

### ISSUE THREAD

**Issue by Lolothepro** [Soaryn/XyCraftTracker#50]
### Mod Title

XyCraft Core

### Minecraft Version

1.21.0

### Severity

Error in log

### NeoForge Version

21.0.64-beta

### Describe the Suggestion

```
 An error occured while initializing client-only XyCraft Core integration!
java.lang.ClassNotFoundException: tv.soaryn.xycraft.core.client.render.model.ConnectedTextureModel$Data
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?] {}
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?] {}
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:216) ~[securejarhandler-3.0.8.jar:?] {}
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?] {}
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:216) ~[securejarhandler-3.0.8.jar:?] {}
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?] {}
	at java.base/java.lang.Class.forName0(Native Method) ~[?:?] {re:mixin}
	at java.base/java.lang.Class.forName(Class.java:421) ~[?:?] {re:mixin}
	at java.base/java.lang.Class.forName(Class.java:412) ~[?:?] {re:mixin}
	at TRANSFORMER/framedblocks@10.1.0/xfacthd.framedblocks.common.compat.xycraft.XyCraftCompat$GuardedClientAccess.init(XyCraftCompat.java:38) ~[FramedBlocks-10.1.0.jar%23364!/:?] {re:classloading}
	at TRANSFORMER/framedblocks@10.1.0/xfacthd.framedblocks.common.compat.xycraft.XyCraftCompat.init(XyCraftCompat.java:22) ~[FramedBlocks-10.1.0.jar%23364!/:?] {re:classloading}
	at TRANSFORMER/framedblocks@10.1.0/xfacthd.framedblocks.common.compat.CompatHandler.init(CompatHandler.java:30) ~[FramedBlocks-10.1.0.jar%23364!/:?] {re:classloading}
	at TRANSFORMER/framedblocks@10.1.0/xfacthd.framedblocks.FramedBlocks.<init>(FramedBlocks.java:64) ~[FramedBlocks-10.1.0.jar%23364!/:?] {re:classloading}
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?] {}
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?] {}
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?] {}
	at MC-BOOTSTRAP/fml_loader@4.0.15/net.neoforged.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:115) ~[loader-4.0.15.jar%23141!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.15/net.neoforged.fml.ModLoader.lambda$constructMods$3(ModLoader.java:153) ~[loader-4.0.15.jar%23141!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.15/net.neoforged.fml.ModLoader.lambda$dispatchParallelTask$7(ModLoader.java:231) ~[loader-4.0.15.jar%23141!/:4.0] {}
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934) [?:?] {re:mixin}
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911) [?:?] {}
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483) [?:?] {}
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) [?:?] {}
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) [?:?] {}
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) [?:?] {re:mixin,re:computing_frames}
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) [?:?] {re:mixin,re:computing_frames}
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) [?:?] {re:mixin}
[15:54:55] [modloading-worker-0/INFO] [me.tr.be.BetterF3NeoForge/]: [BetterF3] All done!
```

This error with FramedBlock

### Reproduction Steps

Launch FramedBlocks with XyCraft Core

**Comment by Soaryn** [comment]
Let me talk to XFact, I moved it to a different package so the reflection used on Framed blocks may be tripping

**Comment by Soaryn** [comment]
Added custom support for Framed blocks in `0.7.29`, Framed blocks will also need an update to solve this migration. No need to mention it to XFactHD though, as we were discussing the solutions already! Sorry for the inconveniences. XyCraft will be updated later today (an hour or two to solve the other bugs mentioned is my estimate)
